Last minute fixes

diff --git a/bin/blom-article b/bin/blom-article
--- a/bin/blom-article
+++ b/bin/blom-article
@@ -4,7 +4,7 @@
 title=''
 tag_list='[]'
 article_class=''
-template_path=$PWD
+template_path=''
 article_path=$PWD
 
 while getopts ":t:c:g:T:A:" opt; do
@@ -33,6 +33,11 @@ while getopts ":t:c:g:T:A:" opt; do
 	esac
 done
 
+if [ -z "$template_path" ]; then
+	echo "Error: no template path provided. Exiting.."
+	exit 64
+fi
+
 editday_raw=$(stat $article_path/content.md -c %z)
 host_url="http://www.ratan.blog"
 relative_url="/${article_path##*/}"
@@ -59,7 +64,10 @@ if [ -f "$article_path/item.json" ]; then
 		fi
 	fi
 	if [ "$tag_list" = '[]' ]; then
-		tag_list=$(cat $article_path/item.json | jq '.tags')
+		old_tag_list=$(cat $article_path/item.json | jq '.tags')
+		if [ -n "$old_tag_list" ]; then
+			tag_list=$old_tag_list
+		fi
 	fi
 else
 	writeday_item=$editday_item
